apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-my-thingsboard-pg-postgresql-0
  labels:
    app.kubernetes.io/component: postgresql
    app.kubernetes.io/instance: my-thingsboard
    app.kubernetes.io/name: pg
spec:
  capacity:
    storage: 10Gi # Specify the appropriate storage capacity
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # Or use Delete as per your policy
  storageClassName: local-disk
  local:
    path: /mnt # Update this path as per your local disk path
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 192.168.3.38 # Replace with the name of the node where this PV should be available
